version: '3.8'
services:
  config-server:
    container_name: config-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/config-repo
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/davidjmc/config-server.git
      - SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS=config-repo

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./backend/init-db:/docker-entrypoint-initdb.d

  node-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-api
    ports:
      - "3000:3000"
    depends_on:
      - config-server
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - node-api

volumes:
  mongodb-data:


