version: '3.8'

services:
  config-server:
    image: springcloud/spring-cloud-config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/davidjmc/config-server
    volumes:
      - ./config-repo:/config-repo

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  node-api:
    build: ./backend/node-api
    container_name: node-api
    environment:
      - MONGODB_URL=mongodb://mongodb:27017  # Link para o serviço MongoDB no Docker
      - DB_NAME=meus_produtos
    depends_on:
      - mongodb
      - config-server
    ports:
      - "3000:3000"

volumes:
  mongodb-data:
