server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/davidjmc/config-server
          search-paths: config-repo
          clone-on-start: true
